### ISSUE TITLE
[Bug]: Quotes don't get post-processing

### ISSUE THREAD

**Issue by BackHDLP** [katniny/transsocial#11]
### Describe the bug

Quoting a note containing anything that would get extra processing – i.e. contains links, mentions, or new lines – doesn't get that.

Original note:
![image](https://github.com/user-attachments/assets/8e77cf94-9be4-4039-8f00-eb133303ff7e)

Quoted:
![image](https://github.com/user-attachments/assets/6e5f08b1-6d71-43a0-96be-0aa66f1dea9d)

### How should it be normally?

The quoted note gets its links and mentions turned into clickable links, and its new lines turned into `<br>` elements

### Steps to reproduce

1. have a note with any of that markup
2. quote that note

### Additional notes

Twemoji does get processed

### Other

- [X] I could replicate this in a local dev environment
- [X] I will fix this issue myself
- [X] I have searched for similar issues

### Platform

Desktop/Laptop (Browser)

### App

None

**Comment by katniny** [comment]
fixing rn

**Comment by katniny** [comment]
https://github.com/katniny/transsocial/commit/9a6f0b35af3aeb99153fda9c025099a1d3dfef83
