### ISSUE TITLE
[Bug]: Header in android app is broken

### ISSUE THREAD

**Issue by miku4k** [katniny/transsocial#21]
### Describe the bug

see at the top of the screenshot
![Screenshot_20241027-162137](https://github.com/user-attachments/assets/245e8bbf-fb4b-43aa-9415-5a89b58b02a5)

### How should it be normally?

see at the top of the screenshot
![Screenshot_20241027-182918](https://github.com/user-attachments/assets/eddcc37c-8fb0-4e58-9594-4f5b6c344ed7)

### Steps to reproduce

Open the androoid app
look at the top

### Other

- [ ] I could replicate this in a local dev environment
- [ ] I will fix this issue myself
- [X] I have searched for similar issues

### Platform

Phone (App)

### App

Android APK

**Comment by katniny** [comment]
https://github.com/katniny/transsocial/commit/770610f1e586d17ba3401f8483f26ed58c1525f0
