### ISSUE TITLE
[Feature]: Basic Markdown Support

### ISSUE THREAD

**Issue by BackHDLP** [katniny/transsocial#7]
### Describe your feature

Allow formatting via Markdown. 
This includes:
- [x] \*bold\*, \_italics\_, \~strikethrough\~, \`monospace\`
- [x] \```
  Monospace blocks
  \```
- [x] \- Lists
- [x] \> Blockquotes
- [x] Escaping using \

It may also include:
- [ ] :emojis:
- [x] \# Headings
- [ ] \[Links](url)

### How would your feature improve TransSocial?

It allows for more expressiveness and readability

### Additional notes

This is still very far out of reach and very low priority. 

### Other

- [ ] I will implement this feature myself
- [X] I have searched for similar issues

**Comment by katniny** [comment]
will look into it

**Comment by katniny** [comment]
https://github.com/katniny/transsocial/commit/e547cf4ddde1da8d7d8aedba7df197f45c5947a8

**Comment by BackHDLP** [comment]
You're actually insane I did not expect this to happen even this month, let alone today
